local C = require("catppuccin.palettes").get_palette()

return {
  rosewater = C.rosewater,
  flamingo = C.flamingo,
  pink = C.pink,
  mauve = C.mauve,
  red = C.red,
  maroon = C.maroon,
  peach = C.peach,
  yellow = C.yellow,
  green = C.green,
  teal = C.teal,
  sky = C.sky,
  sapphire = C.sapphire,
  blue = C.blue,
  lavender = C.lavender,
  text = C.text,
  subtext1 = C.subtext1,
  subtext0 = C.subtext0,
  overlay2 = C.overlay2,
  overlay1 = C.overlay1,
  overlay0 = C.overlay0,
  surface2 = C.surface2,
  surface1 = C.surface1,
  surface0 = C.surface0,
  base = C.base,
  mantle = C.mantle,
  crust = C.crust,
}
