local C = require("kanagawa.colors").setup().palette

return {
  -- Bg Shades
  sumiInk0 = C.sumiInk0,
  sumiInk1 = C.sumiInk1,
  sumiInk2 = C.sumiInk2,
  sumiInk3 = C.sumiInk3,
  sumiInk4 = C.sumiInk4,
  sumiInk5 = C.sumiInk5,
  sumiInk6 = C.sumiInk6,

  -- Popup and Floats
  waveBlue1 = C.waveBlue1,
  waveBlue2 = C.waveBlue2,

  -- Diff and Git
  winterGreen = C.winterGreen,
  winterYellow = C.winterYellow,
  winterRed = C.winterRed,
  winterBlue = C.winterBlue,
  autumnGreen = C.autumnGreen,
  autumnRed = C.autumnRed,
  autumnYellow = C.autumnYellow,

  -- Diag
  samuraiRed = C.samuraiRed,
  roninYellow = C.roninYellow,
  waveAqua1 = C.waveAqua1,
  dragonBlue = C.dragonBlue,

  -- Fg and Comments
  oldWhite = C.oldWhite,
  fujiWhite = C.fujiWhite,
  fujiGray = C.fujiGray,

  oniViolet = C.oniViolet,
  oniViolet2 = C.oniViolet2,
  crystalBlue = C.crystalBlue,
  springViolet1 = C.springViolet1,
  springViolet2 = C.springViolet2,
  springBlue = C.springBlue,
  lightBlue = C.lightBlue,
  waveAqua2 = C.waveAqua2,

  -- waveAqua2  = "#68AD99",
  -- waveAqua4  = "#7AA880",
  -- waveAqua5  = "#6CAF95",
  -- waveAqua3  = "#68AD99",

  springGreen = C.springGreen,
  boatYellow1 = C.boatYellow1,
  boatYellow2 = C.boatYellow2,
  carpYellow = C.carpYellow,

  sakuraPink = C.sakuraPink,
  waveRed = C.waveRed,
  peachRed = C.peachRed,
  surimiOrange = C.surimiOrange,
  katanaGray = C.katanaGray,

  dragonBlack0 = C.dragonBlack0,
  dragonBlack1 = C.dragonBlack1,
  dragonBlack2 = C.dragonBlack2,
  dragonBlack3 = C.dragonBlack3,
  dragonBlack4 = C.dragonBlack4,
  dragonBlack5 = C.dragonBlack5,
  dragonBlack6 = C.dragonBlack6,

  dragonWhite = C.dragonWhite,
  dragonGreen = C.dragonGreen,
  dragonGreen2 = C.dragonGreen2,
  dragonPink = C.dragonPink,
  dragonOrange = C.dragonOrange,
  dragonOrange2 = C.dragonOrange2,
  dragonGray = C.dragonGray,
  dragonGray2 = C.dragonGray2,
  dragonGray3 = C.dragonGray3,
  dragonBlue2 = C.dragonBlue2,
  dragonViolet = C.dragonViolet,
  dragonRed = C.dragonRed,
  dragonAqua = C.dragonAqua,
  dragonAsh = C.dragonAsh,
  dragonTeal = C.dragonTeal,
  dragonYellow = C.dragonYellow,
  -- "#8a9aa3",

  lotusInk1 = C.lotusInk1,
  lotusInk2 = C.lotusInk2,
  lotusGray = C.lotusGray,
  lotusGray2 = C.lotusGray2,
  lotusGray3 = C.lotusGray3,
  lotusWhite0 = C.lotusWhite0,
  lotusWhite1 = C.lotusWhite1,
  lotusWhite2 = C.lotusWhite2,
  lotusWhite3 = C.lotusWhite3,
  lotusWhite4 = C.lotusWhite4,
  lotusWhite5 = C.lotusWhite5,
  lotusViolet1 = C.lotusViolet1,
  lotusViolet2 = C.lotusViolet2,
  lotusViolet3 = C.lotusViolet3,
  lotusViolet4 = C.lotusViolet4,
  lotusBlue1 = C.lotusBlue1,
  lotusBlue2 = C.lotusBlue2,
  lotusBlue3 = C.lotusBlue3,
  lotusBlue4 = C.lotusBlue4,
  lotusBlue5 = C.lotusBlue5,
  lotusGreen = C.lotusGreen,
  lotusGreen2 = C.lotusGreen2,
  lotusGreen3 = C.lotusGreen3,
  lotusPink = C.lotusPink,
  lotusOrange = C.lotusOrange,
  lotusOrange2 = C.lotusOrange2,
  lotusYellow = C.lotusYellow,
  lotusYellow2 = C.lotusYellow2,
  lotusYellow3 = C.lotusYellow3,
  lotusYellow4 = C.lotusYellow4,
  lotusRed = C.lotusRed,
  lotusRed2 = C.lotusRed2,
  lotusRed3 = C.lotusRed3,
  lotusRed4 = C.lotusRed4,
  lotusAqua = C.lotusAqua,
  lotusAqua2 = C.lotusAqua2,
  lotusTeal1 = C.lotusTeal1,
  lotusTeal2 = C.lotusTeal2,
  lotusTeal3 = C.lotusTeal3,
  lotusCyan = C.lotusCyan,
}
