local C = require("tokyonight.colors").setup()

return {
  bg_dark = C.bg_dark,
  bg = C.bg,
  bg_highlight = C.bg_highlight,
  terminal_black = C.terminal_black,
  fg = C.fg,
  fg_dark = C.fg_dark,
  fg_gutter = C.fg_gutter,
  dark3 = C.dark3,
  comment = C.comment,
  dark5 = C.dark5,
  blue0 = C.blue0,
  blue = C.blue,
  cyan = C.cyan,
  blue1 = C.blue1,
  blue2 = C.blue2,
  blue5 = C.blue5,
  blue6 = C.blue6,
  blue7 = C.blue7,
  magenta = C.magenta,
  magenta2 = C.magenta2,
  purple = C.purple,
  orange = C.orange,
  yellow = C.yellow,
  green = C.green,
  green1 = C.green1,
  green2 = C.green2,
  teal = C.teal,
  red = C.red,
  red1 = C.red1,
  -- HACK: Don't add the git stuff, since IDK how I'd do it.
}
