return {
  dashboard = true,
  fidget = true,
  gitsigns = true,
  leap = true,
  lsp_saga = true,
  mason = true,
  markdown = true,
  mini = true,
  nvimtree = true,
  treesitter = true,
  cmp = true,
  telescope = true,
  which_key = true,
}
