require("catppuccin").setup({
  custom_highlights = function(colors)
    return {
      NormalFloat = { bg = colors.crust },
      FloatBorder = { bg = colors.crust, fg = colors.crust },
      VertSplit = { bg = colors.base, fg = colors.surface0 },
      CursorLineNr = { fg = colors.mauve, style = { "bold" } },
      Pmenu = { bg = colors.crust, fg = "" },
      PmenuSel = { bg = colors.surface0, fg = "" },
      TelescopeSelection = { bg = colors.surface0 },
      TelescopePromptCounter = { fg = colors.mauve, style = { "bold" } },
      TelescopePromptPrefix = { bg = colors.surface0 },
      TelescopePromptNormal = { bg = colors.surface0 },
      TelescopeResultsNormal = { bg = colors.mantle },
      TelescopePreviewNormal = { bg = colors.crust },
      TelescopePromptBorder = { bg = colors.surface0, fg = colors.surface0 },
      TelescopeResultsBorder = { bg = colors.mantle, fg = colors.mantle },
      TelescopePreviewBorder = { bg = colors.crust, fg = colors.crust },
      TelescopePromptTitle = { fg = colors.surface0, bg = colors.surface0 },
      TelescopeResultsTitle = { fg = colors.mantle, bg = colors.mantle },
      TelescopePreviewTitle = { fg = colors.crust, bg = colors.crust },
      IndentBlanklineChar = { fg = colors.surface0 },
      IndentBlanklineContextChar = { fg = colors.surface2 },
      GitSignsChange = { fg = colors.peach },
      NvimTreeIndentMarker = { link = "IndentBlanklineChar" },
      NvimTreeExecFile = { fg = colors.text },
    }
  end,
  styles = {
    comments = { "italic" },
    conditionals = { "italic" },
    loops = { "bold" },
    functions = { "bold" },
    keywords = { "bold" },
    strings = {},
    variables = {},
    numbers = { "bold" },
    booleans = { "bold" },
    properties = {},
    types = { "bold" },
    operators = {},
  },
  integrations = {
    mini = true,
    cmp = false,
    telescope = false,
    aerial = false,
    barbar = false,
    barbecue = false,
    beacon = false,
    coc_nvim = false,
    dashboard = true,
    fern = false,
    gitsigns = true,
    harpoon = true,
    hop = false,
    leap = false,
    lightspeed = false,
    lsp_saga = true,
    markdown = true,
    mason = true,
    neotree = false,
    neogit = false,
    neotest = false,
    noice = false,
    dap = false,
    native_lsp = {
      enable = true,
    },
    navic = false,
    notify = false,
    sematntic_tokens = false,
    nvimtree = true,
    treesitter_context = false,
    treesitter = true,
    ts_rainbow = false,
    ts_rainbow2 = false,
    octo = false,
    overseer = false,
    pounce = false,
    symbols_outline = false,
    telekasten = false,
    lsp_trouble = true,
    gitgutter = false,
    illuminate = false,
    vim_sneak = false,
    vimwiki = false,
    which_key = false,
  },
})
