vim.defer_fn(function()
  require("configs.ui.animate")
  require("configs.ui.indent")
  require("configs.ui.matcher")
  require("configs.editor.comment")
  require("configs.editor.motion")
  require("ufo").closeAllFolds()
end, 1000)
