local opts = {
  { name = "mapleader", value = " ", modifier = vim.g },
  { name = "shiftwidth", value = 2, modifier = vim.o },
  { name = "undofile", value = true, modifier = vim.o },
  { name = "backup", value = false, modifier = vim.o },
  { name = "writebackup", value = false, modifier = vim.o },
  { name = "mouse", value = "a", modifier = vim.o },
  { name = "swapfile", value = false, modifier = vim.o },
  { name = "hidden", value = true, modifier = vim.o },
  { name = "clipboard", value = "unnamed,unnamedplus", modifier = vim.o },
  { name = "expandtab", value = true, modifier = vim.o },
  { name = "breakindent", value = true, modifier = vim.o },
  { name = "cursorline", value = true, modifier = vim.o },
  { name = "linebreak", value = true, modifier = vim.o },
  { name = "number", value = true, modifier = vim.o },
  { name = "splitbelow", value = true, modifier = vim.o },
  { name = "splitright", value = true, modifier = vim.o },
  { name = "termguicolors", value = true, modifier = vim.o },
  { name = "showmode", value = false, modifier = vim.o },
  { name = "wrap", value = false, modifier = vim.o },
  { name = "signcolumn", value = "yes", modifier = vim.o },
  { name = "fillchars", value = "eob: ", modifier = vim.o },
  { name = "ignorecase", value = true, modifier = vim.o },
  { name = "incsearch", value = true, modifier = vim.o },
  { name = "infercase", value = true, modifier = vim.o },
  { name = "smartcase", value = true, modifier = vim.o },
  { name = "smartindent", value = true, modifier = vim.o },
  { name = "completeopt", value = "menuone,noinsert,noselect", modifier = vim.o },
  { name = "virtualedit", value = "onemore", modifier = vim.o },
  { name = "formatoptions", value = "qjl1", modifier = vim.o },
  { name = "splitkeep", value = "screen", modifier = vim.o },
  { name = "list", value = true, modifier = vim.o },
  { name = "listchars", value = "eol:↴,space:⋅", modifier = vim.o }
}

local async = require("util.setoptions")
async(opts)
